/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora;

import com.mycompany.calculadora.controle.CalcControladora;
import com.mycompany.calculadora.enums.EnumOperacao;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

/**
 *
 * @author brenin
 */
public class InterfaceCalc extends javax.swing.JFrame {
    
    private CalcControladora calcControladora;
    
    
    private EnumOperacao ultimaOperacao;
    private double valorAnterior = 0;
    private boolean aguardandoNovoNumero = false;

    
    

    /**
     * Creates new form InterfaceCalc
     */
    public InterfaceCalc() {
        initComponents();
        calcControladora = new CalcControladora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btClear = new javax.swing.JButton();
        btZero = new javax.swing.JButton();
        btDivisao = new javax.swing.JButton();
        btIgual = new javax.swing.JButton();
        btUm = new javax.swing.JButton();
        btDois = new javax.swing.JButton();
        btTres = new javax.swing.JButton();
        btSoma = new javax.swing.JButton();
        btQuatro = new javax.swing.JButton();
        btCinco = new javax.swing.JButton();
        btSeis = new javax.swing.JButton();
        btSubtracao = new javax.swing.JButton();
        btSete = new javax.swing.JButton();
        btOito = new javax.swing.JButton();
        btNove = new javax.swing.JButton();
        btMultiplicacao = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        tfValor.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfValor.setText("0,00");
        tfValor.setActionCommand("<Not Set>");
        tfValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.control);
        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        btClear.setText("CLEAR");
        btClear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel1.add(btClear);

        btZero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btZero.setText("0");
        btZero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZeroActionPerformed(evt);
            }
        });
        jPanel1.add(btZero);

        btDivisao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDivisao.setText("/");
        btDivisao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivisaoActionPerformed(evt);
            }
        });
        jPanel1.add(btDivisao);

        btIgual.setBackground(new java.awt.Color(255, 102, 0));
        btIgual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btIgual.setForeground(new java.awt.Color(255, 255, 255));
        btIgual.setText("=");
        btIgual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgualActionPerformed(evt);
            }
        });
        jPanel1.add(btIgual);

        btUm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btUm.setText("1");
        btUm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUmActionPerformed(evt);
            }
        });
        jPanel1.add(btUm);

        btDois.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDois.setText("2");
        btDois.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoisActionPerformed(evt);
            }
        });
        jPanel1.add(btDois);

        btTres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btTres.setText("3");
        btTres.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTresActionPerformed(evt);
            }
        });
        jPanel1.add(btTres);

        btSoma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSoma.setText("+");
        btSoma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSomaActionPerformed(evt);
            }
        });
        jPanel1.add(btSoma);

        btQuatro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btQuatro.setText("4");
        btQuatro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuatroActionPerformed(evt);
            }
        });
        jPanel1.add(btQuatro);

        btCinco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCinco.setText("5");
        btCinco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCincoActionPerformed(evt);
            }
        });
        jPanel1.add(btCinco);

        btSeis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSeis.setText("6");
        btSeis.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeisActionPerformed(evt);
            }
        });
        jPanel1.add(btSeis);

        btSubtracao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSubtracao.setText("-");
        btSubtracao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubtracaoActionPerformed(evt);
            }
        });
        jPanel1.add(btSubtracao);

        btSete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSete.setText("7");
        btSete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeteActionPerformed(evt);
            }
        });
        jPanel1.add(btSete);

        btOito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btOito.setText("8");
        btOito.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOitoActionPerformed(evt);
            }
        });
        jPanel1.add(btOito);

        btNove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btNove.setText("9");
        btNove.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNoveActionPerformed(evt);
            }
        });
        jPanel1.add(btNove);

        btMultiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btMultiplicacao.setText("X");
        btMultiplicacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiplicacaoActionPerformed(evt);
            }
        });
        jPanel1.add(btMultiplicacao);

        btFechar.setBackground(new java.awt.Color(255, 51, 51));
        btFechar.setForeground(new java.awt.Color(255, 255, 255));
        btFechar.setText("FECHAR");
        btFechar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        jPanel1.add(btFechar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addComponent(tfValor))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
      tfValor.setText("0,00");
      calcControladora.zerar(); // Zera estado interno (se necessário)
    
      valorAnterior = 0;
      ultimaOperacao = null;
      aguardandoNovoNumero = false;
    }//GEN-LAST:event_btClearActionPerformed

    private void btZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZeroActionPerformed
        // TODO add your handling code here:
        digitaN("0");
    }//GEN-LAST:event_btZeroActionPerformed

    private void btNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNoveActionPerformed
        // TODO add your handling code here:
        digitaN("9");
    }//GEN-LAST:event_btNoveActionPerformed

    private void btUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUmActionPerformed
        // TODO add your handling code here:
        digitaN("1");
    }//GEN-LAST:event_btUmActionPerformed

    private void btDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoisActionPerformed
        // TODO add your handling code here:
        digitaN("2");
    }//GEN-LAST:event_btDoisActionPerformed

    private void btTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTresActionPerformed
        // TODO add your handling code here:
        digitaN("3");
    }//GEN-LAST:event_btTresActionPerformed

    private void btQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuatroActionPerformed
        // TODO add your handling code here:
        digitaN("4");
    }//GEN-LAST:event_btQuatroActionPerformed

    private void btCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCincoActionPerformed
        // TODO add your handling code here:
        digitaN("5");
    }//GEN-LAST:event_btCincoActionPerformed

    private void btSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeisActionPerformed
        // TODO add your handling code here:
        digitaN("6");
    }//GEN-LAST:event_btSeisActionPerformed

    private void btSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeteActionPerformed
        // TODO add your handling code here:
        digitaN("7");
    }//GEN-LAST:event_btSeteActionPerformed

    private void btOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOitoActionPerformed
        // TODO add your handling code here:
        digitaN("8");
    }//GEN-LAST:event_btOitoActionPerformed

    private void btSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomaActionPerformed
     valorAnterior = StringToDouble(tfValor.getText());  // Salva o número atual
    ultimaOperacao = EnumOperacao.SOMA;  // Define a operação como soma
    aguardandoNovoNumero = true;  // Indica que estamos aguardando um novo número
    tfValor.setText("");  // Limpa o campo de texto para o próximo número
    }//GEN-LAST:event_btSomaActionPerformed

    private void btSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtracaoActionPerformed
        valorAnterior = StringToDouble(tfValor.getText());  // Salva o número atual
    ultimaOperacao = EnumOperacao.SUBTRACAO;  // Define a operação como soma
    aguardandoNovoNumero = true;  // Indica que estamos aguardando um novo número
    tfValor.setText("");  // Limpa o campo de texto para o próximo número
    }//GEN-LAST:event_btSubtracaoActionPerformed

    private void btMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplicacaoActionPerformed
        valorAnterior = StringToDouble(tfValor.getText());  // Salva o número atual
    ultimaOperacao = EnumOperacao.MULTIPLICACAO;  // Define a operação como soma
    aguardandoNovoNumero = true;  // Indica que estamos aguardando um novo número
    tfValor.setText("");  // Limpa o campo de texto para o próximo número
    }//GEN-LAST:event_btMultiplicacaoActionPerformed

    private void btDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivisaoActionPerformed
        valorAnterior = StringToDouble(tfValor.getText());  // Salva o número atual
    ultimaOperacao = EnumOperacao.SOMA;  // Define a operação como soma
    aguardandoNovoNumero = true;  // Indica que estamos aguardando um novo número
    tfValor.setText("");  // Limpa o campo de texto para o próximo número
    }//GEN-LAST:event_btDivisaoActionPerformed

    private void btIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgualActionPerformed
        // TODO add your handling code here:
        double valorAtual = StringToDouble(tfValor.getText());
        double resultado = calcControladora.RealizarOperacao(ultimaOperacao, valorAnterior, valorAtual);
        tfValor.setText(DoubleToString(resultado));
        aguardandoNovoNumero = false;
    }//GEN-LAST:event_btIgualActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btFecharActionPerformed

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
        // TODO add your handling code here:
        tfValor.setText(DoubleToString(calcControladora.getTotal()));
    }//GEN-LAST:event_tfValorActionPerformed

    private double StringToDouble(String numero){
        NumberFormat nf = NumberFormat.getInstance();
        Double dv = 0.0;
        try{
            dv = nf.parse(numero).doubleValue();
        }catch (ParseException ex){
            
        }
        return dv;
        
        
    }
    private String DoubleToString(Double numero){
        if(numero != null){
            DecimalFormat formato = new DecimalFormat("##,###,###,##0.00", new DecimalFormatSymbols(new Locale("pt", "BR")));
            formato.setParseBigDecimal(true);
            return formato.format(numero);
            
        }
        return"";
    }
    
    private void digitaN(String caractere){
    if (aguardandoNovoNumero) {
        // Começando a digitar o novo número, então limpa
        if (caractere.equals(",")) {
            tfValor.setText("0,");
        } else {
            tfValor.setText(caractere);
        }
        aguardandoNovoNumero = false;
        return;
    }

    // Se o campo estiver com 0,00, substitui
    if (tfValor.getText().equals("0,00")){
        tfValor.setText(caractere);
    } else {
        // Impede dois caracteres "," (vírgula)
        if(caractere.equals(",") && tfValor.getText().contains(",")){
            // não faz nada
        } else {
            tfValor.setText(tfValor.getText().concat(caractere));
        }
    }
}

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCinco;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDivisao;
    private javax.swing.JButton btDois;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btIgual;
    private javax.swing.JButton btMultiplicacao;
    private javax.swing.JButton btNove;
    private javax.swing.JButton btOito;
    private javax.swing.JButton btQuatro;
    private javax.swing.JButton btSeis;
    private javax.swing.JButton btSete;
    private javax.swing.JButton btSoma;
    private javax.swing.JButton btSubtracao;
    private javax.swing.JButton btTres;
    private javax.swing.JButton btUm;
    private javax.swing.JButton btZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
